stages:
  - build
  - test
  - security
  - quality

default:
  image: node:18

# 1. Збірка проєкту
build_app:
  stage: build
  script:
    - echo "Building the app..."
    - npm install
  cache:
    paths:
      - node_modules/

# 2. Тести (якщо є)
test_app:
  stage: test
  script:
    - echo "Running tests..."
    # Якщо тестів немає, команда не впаде завдяки "|| true"
    - npm test || echo "No tests specified"

# 3. Сканування безпеки (Trivy)
trivy_scan:
  stage: security
  image:
    name: aquasecurity/trivy:latest
    entrypoint: ['']
  script:
    - echo "Scanning for vulnerabilities..."
    # Скануємо поточну папку (fs .)
    # Шукаємо тільки серйозні проблеми (HIGH, CRITICAL)
    # --exit-code 0 означає "не зупиняти пайплайн, навіть якщо знайшли проблеми"
    - trivy fs . --severity HIGH,CRITICAL --format table --exit-code 0
  allow_failure: true # Дозволяємо пайплайну йти далі, навіть якщо є вразливості

# 4. Аналіз якості коду (SonarCloud)
sonarqube-check:
  stage: quality
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: ['']
  variables:
    SONAR_USER_HOME: '${CI_PROJECT_DIR}/.sonar'
    GIT_DEPTH: '0'
  cache:
    key: '${CI_JOB_NAME}'
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=123.stepanzdeb_movie_picker
      -Dsonar.organization=123-stepanzdeb
  allow_failure: true
  only:
    - main
